### ISSUE TITLE
connect SUMO to Unity3D

### ISSUE THREAD

**Issue by ghost** [dalugoga/sumo-unity-distributed-ped-sim#1]
Hello, how can I connect SUMO to Unity3D? I have cloned your projects and simulation is running but unfortunately connection between Unity3D with SUMO is not working.

**Comment by ghost** [comment]
how did you sync SUMO with Unity3D?
https://www.youtube.com/watch?v=3TADoA1MNI0

**Comment by ghost** [comment]
do you have this file project(github)?
https://www.youtube.com/watch?v=r1qbtAOUi7s

**Comment by dalugoga** [comment]
To run the python script you must install the zmq (ZeroMQ) package. https://zeromq.org/languages/python/

What problems are you having?

**Comment by ghost** [comment]
Thanks, I was running python scripts back then and python synced with unity3d together but when I run the SUMO then as 3D needs to display in unity3d and I believe that SUMO with unity3D have no connection together and how can I solve the problem?

**Comment by Ahmad1441** [comment]
@dalugoga 

Simulation runs and it is great. However, when a pedestrian steps on crosswalk (zebra area), Sumo stops and generate the following warning:

_Traceback (most recent call last):
  File "C:\Users\ahmad\sumo-unity-distributed-pedestrian-simulator\SUMO Network\runner.py", line 272, in <module>
    run()
  File "C:\Users\ahmad\sumo-unity-distributed-pedestrian-simulator\SUMO Network\runner.py", line 189, in run
    traci.simulationStep()
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\__init__.py", line 127, in simulationStep
    responses = _connections[""].simulationStep(step)
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\connection.py", line 323, in simulationStep
    result = self._sendExact()
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\connection.py", line 99, in _sendExact
    raise FatalTraCIError("connection closed by SUMO")
traci.exceptions.FatalTraCIError: connection closed by SUMO

Process finished with exit code 1_

Can you please help me with this?
